---
#
# Ansible will automatically read this file prior to executing tasks.
#

homebrew_installed_packages:
  - bash
  - bash-completion
  - bat
  - gawk
  - gh
  - git
  - imagemagick
  - jq
  - nmap
  - nvm
  - poetry
  - pv
  - pyenv
  - sqlite
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - anki
  - authy
  - discord
  - figma
  - firefox
  - google-chrome
  - karabiner-elements
  - keepassxc
  - kitty
  - microsoft-office
  - postman
  - signal
  - slack
  - spotify
  - zoom

# Do NOT install Xcode using this role.
mas_installed_apps:
  - { id: 682658836, name: "GarageBand (10.4.3)"}

# Set to 'true' to configure Xcode and dependent tools. (Requires that mas is installed.)
configure_xcode: true

xcode:
  - { id: 497799835, name: "Xcode (12.5.1)", upgrade: false }

xcode_dependent_packages:
  - swift-format

xcode_upgrade_dependent_packages: true

# Set to 'true' to configure the Mac Dock via dockutil.
configure_dock: true

dockitems_remove:
  - "App Store"
  - Calendar
  - Contacts
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - "System Preferences"
  - TV

dockitems_persist:
 - name: "kitty"
   path: "/Applications/kitty.app/"
   pos: 1
 - name: "KeePassXC"
   path: "/Applications/KeePassXC.app/"
   pos: 2
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app"
   pos: 3
 - name: "Anki"
   path: "/Applications/Anki.app"
   pos: 4
 - name: "Mail"
   path: "/System/Applications/Mail.app/"
   pos: 5
